# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4671e54953b8c7e1e2426036a4203771f2d9d2c7db14d9f10e53e0b3904192c14e3f583c4f6e040717f85a0f144dedd4f292340aa54c0a86c792921b175a6543

test:
  secret_key_base: ff94ba1ab5fb99ea28266f2370b0571019a39e09d4a5fc7e0f8ce73a5efffb8f683ce2621d9b8a8c96edbe4e0a6c2dbd8db1bced10c0041184be1b8478400995

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
